#!/usr/bin/env python3
import ee
import argparse

def main(args):
    None

if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--coords",
        nargs=2,
        type=str,
        help="Area of Interest (AOI) defined by lat, lon coordiates",
    )

    args = parser.parse_args()

    main(args)
