#!/usr/bin/env python3
import tkinter as tk
import webbrowser
from tkinter import filedialog


def OpenUrl(url):
    webbrowser.open_new(url)


# Function for opening the
# file explorer window
def browseFiles(label):
    filename = filedialog.askopenfilename(
        initialdir="./",
        title="Select a File",
        filetypes=(("CSV files", "*.csv*"), ("all files", "*.*")),
    )

    label.configure(text="File Opened: " + filename)


def main():
    window = tk.Tk()
    window.geometry("1000x500")
    window.config(background="white")

    title_frame = tk.Frame(window, background="#D2E2FB", bd=1, relief="flat")
    title_frame.pack()

    title = tk.Label(
        title_frame,
        text="Sea Ice Phenology Detection\nby ICE Lab at University of Victoria",
        width=50,
        height=4,
        fg="black",
        font="50",
    )
    title.config(background="white")
    title.pack()

    url = "https://sangwon.users.earthengine.app/view/seaicephenology"

    button_MODIS = tk.Button(
        window, text="Retrieve MODIS data", command=lambda aurl=url: OpenUrl(aurl)
    )
    button_MODIS.pack(side="top")

    FE_frame = tk.Frame(window)

    label_file_explorer = tk.Label(FE_frame, text="File Opened: ", fg="blue")

    button_explore = tk.Button(
        FE_frame,
        text="Browse Files",
        command=lambda label=label_file_explorer: browseFiles(label),
    )
    FE_frame.pack(side="top")
    button_explore.pack(side="left")
    label_file_explorer.pack(side="left")

    button_exit = tk.Button(window, text="Exit", command=exit)
    button_exit.pack(side="top")

    window.mainloop()


if __name__ == "__main__":
    main()
