#!/usr/bin/env python3
from tkinter import *
import webbrowser


def main():
    window = Tk()
    frame = Frame(window)
    frame.pack()

    title = Label(
        text="Sea Ice Phenology Detection\nby ICE Lab at University of Victoria"
    )
    title.pack()

    url = "https://sangwon.users.earthengine.app/view/seaicephenology"

    def OpenUrl(url):
        webbrowser.open_new(url)

    button = Button(
        window, text="Retrieve MODIS data", command=lambda aurl=url: OpenUrl(aurl)
    )

    button.pack()
    window.mainloop()


if __name__ == "__main__":
    main()
