#!/usr/bin/env python3
import argparse
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression


def main(args):
    ts_df = pd.read_csv(args.input, thousands=",")

    for band in ts_df.columns:
        if band.endswith("_interpolate"):
            idx = 30
            while idx < ts_df.shape[0]:
                subset = ts_df[idx - 30 : idx][band].dropna()
                if subset.shape[0] == 30:
                    reg = LinearRegression().fit(
                        np.array([subset.index]).reshape(-1, 1), subset
                    )
                    print(reg.coef_)

                idx += 1
        else:
            continue


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input",
        type=str,
        help="Path to time-series data file (csv)",
        required=True,
    )

    args = parser.parse_args()

    main(args)
