#!/usr/bin/env python3
import os
import pandas as pd

files = os.listdir("./output/trend/")
MO_df = pd.DataFrame()
OW_df = pd.DataFrame()
FO_df = pd.DataFrame()

for f in files:
    if f.endswith(".csv"):
        df = pd.read_csv(f"./output/trend/{f}")
        community = f.split("/")[-1][:-10].replace("_", " ")

        curr_MO = df[["Year", "MO"]].rename({"MO": community}, axis=1)
        if MO_df.empty:
            MO_df = curr_MO
        else:
            MO_df = pd.merge(MO_df, curr_MO, how="outer", on=["Year"])

        curr_OW = df[["Year", "OW"]].rename({"OW": community}, axis=1)
        if OW_df.empty:
            OW_df = curr_OW
        else:
            OW_df = pd.merge(OW_df, curr_OW, how="outer", on=["Year"])

        curr_FO = df[["Year", "FO"]].rename({"FO": community}, axis=1)
        if FO_df.empty:
            FO_df = curr_FO
        else:
            FO_df = pd.merge(FO_df, curr_FO, how="outer", on=["Year"])

MO_df = MO_df.T
MO_df["Count"] = MO_df.count(axis=1, numeric_only=True)
OW_df = OW_df.T
OW_df["Count"] = OW_df.count(axis=1, numeric_only=True)
FO_df = FO_df.T
FO_df["Count"] = FO_df.count(axis=1, numeric_only=True)

MO_df.to_csv("./output/trend_summary/MO_trend_summary.csv")
OW_df.to_csv("./output/trend_summary/OW_trend_summary.csv")
FO_df.to_csv("./output/trend_summary/FO_trend_summary.csv")
