#!/usr/bin/env python3
import argparse
import csv
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sea_ice_phenology.utils import interQuantileMask


def main(args):
    df = pd.read_csv(args.input, thousands=",")

    for phenology in df.columns:
        trend_df = None
        if phenology.endswith("phenology") == False:
            continue
        for k in ["MO", "OW", "FO"]:
            trend = df.drop(df[df[phenology] != k].index).copy()
            trend.index = pd.DatetimeIndex(trend["system:time_start"]).year
            trend[k] = pd.to_datetime(
                trend["system:time_start"], errors="coerce"
            ).dt.dayofyear
            if k in ["PO", "OW"]:
                trend = trend.groupby(trend.index).first()
            else:
                trend = trend.groupby(trend.index).last()

            trend[k] = interQuantileMask(trend[k], low="", high="").drop(
                trend[trend[k] == ""].index
            )

            if trend_df is None:
                trend_df = pd.DataFrame(trend[k])
            else:
                trend_df = trend_df.join(trend[k])

        sns.set_style("dark")
        fig, ax = plt.subplots(figsize=(20, 4))

        p = sns.lineplot(
            data=trend_df,
        )
        p.set_xlabel("Year")
        p.set_ylabel("DOY")

        fig.canvas.manager.set_window_title(
            f"{'.'.join(args.input.split('/')[-1].split('.')[:-1])}_{phenology.split('_phenology')[0]}_trend"
        )

        plt.grid()
        plt.show()

        trend_df.to_csv(
            f"{'.'.join(args.input.split('.')[:-1]).split('_phenology')[0]}_{phenology.split('_phenology')[0]}_trend.csv"
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input",
        type=str,
        help="Path to time-series data file (csv)",
        required=True,
    )

    args = parser.parse_args()

    main(args)
